DISTRO = "cockscreen"
DISTRO_NAME = "Cockscreen Yocto"
DISTRO_VERSION = "master"
DISTRO_CODENAME = "cockscreen"

INIT_MANAGER = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "sysvinit"
VIRTUAL-RUNTIME_initscripts = "initscripts"

DISTRO_FEATURES:append = " opengl alsa ipv4"
DISTRO_FEATURES:remove = " systemd x11 wayland vulkan pulseaudio pam polkit"

PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"
PREFERRED_VERSION_linux-raspberrypi = "6.12%"
PREFERRED_PROVIDER_virtual/libgl = "mesa"
PREFERRED_PROVIDER_virtual/egl = "mesa"
PREFERRED_PROVIDER_virtual/libgles2 = "mesa"

LICENSE_FLAGS_ACCEPTED:append = " commercial commercial_ffmpeg"
