require conf/machine/raspberrypi0-2w-64.conf

MACHINEOVERRIDES =. "cockscreen-rpi0-2w-64:"

ENABLE_SPI_BUS = "1"
ENABLE_I2C = "1"
ENABLE_UART = "1"
DISABLE_OVERSCAN = "1"
GPU_MEM = "128"
VC4DTBO = "vc4-kms-v3d"

CMDLINE_DEBUG = "quiet loglevel=4"
RPI_EXTRA_CONFIG = " \
max_framebuffers=2 \
\ndtoverlay=miniuart-bt \
"

MACHINE_EXTRA_RRECOMMENDS:remove = " \
linux-firmware-rpidistro-bcm43430 \
linux-firmware-rpidistro-bcm43436 \
linux-firmware-rpidistro-bcm43436s \
linux-firmware-rpidistro-bcm43455 \
linux-firmware-rpidistro-bcm43456 \
bluez-firmware-rpidistro-bcm43430b0-hcd \
"
