BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cockscreen"
BBFILE_PATTERN_cockscreen = "^${LAYERDIR}/"
BBFILE_PRIORITY_cockscreen = "9"

LAYERSERIES_COMPAT_cockscreen = "scarthgap whinlatter wrynose"
