; Cockscreen defaults for a generic x86_64 Linux machine
; Load with: --config-file config/x86_64-linux.ini

[runtime]
render_path=qt-shader
window_title=cockscreen
width=1024
height=600
frame_rate=30
scene_file=../scenes/x86_64-linux.scene.json